title: Srinivas Rao Yarra
logo: /assets/img/logo.png
description: I am passionate about new technologies like AI,ML, cloud and Spark
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
